version: "3.2"
services:
  web:
    image: "zeeshan/clinic:v2"
    hostname: "web.myclinic.com"
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "Zeeshan#23"
      DB_HOST: "db.myclinic.com"
      DB_PORT: "3306"
      DB_DATABASE: "clinic"
      
  db:
    image: "mysql:8.0"
    hostname: "db.myclinic.com"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "Zeeshan#23"
      MYSQL_DATABASE: "clinic"

    ports:
      - "3306:3306"
